name: Run Automation Tests

on:
  push:
    branches: [ master ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 1.8
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven

    - name: Run Maven Tests
      run: mvn test

    - name: Upload Test Reports and Screenshots
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: |
          reports/
          screenshots/
          test-output/ # 