name: Run Automation Tests

on:
  push:
    branches: [ master ]
  workflow_dispatch:

permissions:
  contents: read # This is the crucial line to add

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 1.8
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven

    - name: Run Maven Tests
      run: mvn test

    - name: Upload TestNG Report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: testng-reports
        path: test-output/